const { Sequelize, DataTypes } = require('sequelize');
const logger = require('../../../logger');
const dbConfig = require('../../config')[process.env.NODE_ENV];
const sequelize = new Sequelize(dbConfig.url, {
  ...dbConfig,
  logger,
});

const PollResult = sequelize.define('pollResult', {
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4,
    allowNull: false,
    autoIncrement: false,
    onUpdate: 'CASCADE',
    onDelete: 'CASCADE',
  },
  // searchTermId: {
  //   type: DataTypes.UUID,
  //   references: 'searchTerms',
  //   referencesKey: 'id',
  // },
  stationId: {
    type: DataTypes.UUID,
    references: 'stations',
    referencesKey: 'id',
  },
  errorMessage: {
    type: DataTypes.STRING,
    allowNull: true,
  },

  // searchTerm: generated by association in ../index.js
});
module.exports = PollResult;
