const { Sequelize, DataTypes } = require('sequelize');
const logger = require('../../../logger');
const dbConfig = require('../../config')[process.env.NODE_ENV];
const sequelize = new Sequelize(dbConfig.url, {
  ...dbConfig,
  logger,
});
const Song = sequelize.define('song', {
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4,
    allowNull: false,
    autoIncrement: false,
    onUpdate: 'CASCADE',
    onDelete: 'CASCADE',
  },
  // userId: generated by association in ../index.js
  // songId: generated by association in ../index.js
  title: {
    type: DataTypes.STRING,
    allowNull: true,
  },
  itunesTrackId: {
    type: DataTypes.STRING,
    allowNull: true,
  },
  artist: {
    type: DataTypes.STRING,
    allowNull: true,
  },
  album: {
    type: DataTypes.STRING,
    allowNull: true,
  },
  itunesTrackViewUrl: {
    type: DataTypes.STRING,
    allowNull: true,
  },
  artworkUrl: {
    type: DataTypes.STRING,
    allowNull: true,
  },
});
module.exports = Song;
