const { Sequelize, DataTypes } = require("sequelize");
const logger = require("../../../logger");
const sequelize = new Sequelize(process.env.DATABASE_URL, {
  logging: logger.log,
});

const Spin = sequelize.define("spin", {
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4,
    allowNull: false,
    autoIncrement: false,
    onUpdate: "CASCADE",
    onDelete: "CASCADE",
  },
  // AudioBlockId generated by association in ../index.js
  // UserId generated by association in ../index.js
  airtime: {
    type: DataTypes.DATE(6),
    allowNull: false,
  },
  playlistPosition: {
    type: DataTypes.INTEGER,
    allowNull: false,
  },
});

module.exports = Spin;
