const { Sequelize, DataTypes } = require("sequelize");
const logger = require("../../../logger");
const dbConfig = require("../../config")[process.env.NODE_ENV];
const sequelize = new Sequelize(dbConfig.url, {
  ...dbConfig,
  logger,
});
const StationSong = sequelize.define("stationSong", {
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4,
    allowNull: false,
    autoIncrement: false,
    onUpdate: "CASCADE",
    onDelete: "CASCADE",
  },
  // userId: generated by association in ../index.js
  // songId: generated by association in ../index.js
  endOfIntroMSOverride: {
    type: DataTypes.INTEGER,
    allowNull: true,
  },
  endOfMessageMSOverride: {
    type: DataTypes.INTEGER,
    allowNull: true,
  },
  beginningOfOutroMSOverride: {
    type: DataTypes.INTEGER,
    allowNull: true,
  },
  userAffinity: {
    type: DataTypes.DOUBLE,
    defaultValue: 0.0,
  },
});
module.exports = StationSong;
