const { Sequelize, DataTypes } = require('sequelize');
const logger = require('../../../logger');
const dbConfig = require('../../config')[process.env.NODE_ENV];
const sequelize = new Sequelize(dbConfig.url, {
  ...dbConfig,
  logger,
});

const SearchTerm = sequelize.define('searchTerm', {
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4,
    allowNull: false,
    autoIncrement: false,
    onUpdate: 'CASCADE',
    onDelete: 'CASCADE',
  },
  // songId: generated by association in ../index.js
  songId: {
    type: DataTypes.UUID,
    references: 'songs',
    referencesKey: 'id',
    allowNull: true,
  },
  text: {
    type: DataTypes.STRING,
    unique: true,
  },
});

module.exports = SearchTerm;
