const { Sequelize, DataTypes } = require('sequelize');
const logger = require('../../../logger');
const sequelize = new Sequelize(process.env.DATABASE_URL, {
  logging: logger.log,
});

const Station = sequelize.define('station', {
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4,
    allowNull: false,
    autoIncrement: false,
    onUpdate: 'CASCADE',
    onDelete: 'CASCADE',
  },
  // SongId generated by association in ../index.js
  // UserId generated by association in ../index.js
  name: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  streamUrl: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  streamSource: {
    type: DataTypes.STRING,
    allowNull: true,
  },
});

module.exports = Station;
